# Sleep Disorder Analysis

In [1]:
import opendatasets as od
 
od.download(
    "https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset/data")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: mindhawk
Your Kaggle Key: ········
Dataset URL: https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset
Downloading sleep-health-and-lifestyle-dataset.zip to .\sleep-health-and-lifestyle-dataset

100%|█████████████████████████████████████████████████████████████████████████████| 2.54k/2.54k [00:00<00:00, 1.30MB/s]

## Importing all the required Modules

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn import ensemble
from IPython.display import clear_output
import os

## The Data

In [25]:
file =('sleep-health-and-lifestyle-dataset\\Sleep_health_and_lifestyle_dataset.csv')
data = pd.read_csv(file)
 
# displaying the contents of the XLSX file
data.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [26]:
data.Occupation.unique(), len(data.Occupation.unique())

(array(['Software Engineer', 'Doctor', 'Sales Representative', 'Teacher',
        'Nurse', 'Engineer', 'Accountant', 'Scientist', 'Lawyer',
        'Salesperson', 'Manager'], dtype=object),
 11)

In [27]:
data['BMI Category'].unique(), len(data['BMI Category'].unique())

(array(['Overweight', 'Normal', 'Obese', 'Normal Weight'], dtype=object), 4)

In [29]:
data['Sleep Disorder'].unique(), len(data['Sleep Disorder'].unique())

(array(['None', 'Sleep Apnea', 'Insomnia'], dtype=object), 3)

In [28]:
genMap = {'Male': 0, 'Female': 1}
# data['Gender'] = (data['Gender'] == 'Male')? 0:1
data.Gender = data.Gender.map(genMap)
bmiMap = {'Normal': 0, 'Normal Weight': 0, 'Overweight':1, 'Obese': 2}
data['BMI Category'] = data['BMI Category'].map(bmiMap)
data.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,0,27,Software Engineer,6.1,6,42,6,1,126/83,77,4200,None
1,2,0,28,Doctor,6.2,6,60,8,0,125/80,75,10000,None
2,3,0,28,Doctor,6.2,6,60,8,0,125/80,75,10000,None
3,4,0,28,Sales Representative,5.9,4,30,8,2,140/90,85,3000,Sleep Apnea
4,5,0,28,Sales Representative,5.9,4,30,8,2,140/90,85,3000,Sleep Apnea

In [12]:
val = data.values

In [17]:
data.describe()

,Person ID,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.132086,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,0.795657,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,5.800000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.400000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.200000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,7.800000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,8.500000,9.000000,90.000000,8.000000,86.000000,10000.000000